# railway.toml

[[service]]
name = "backend"
path = "backend"
language = "Node" # Changed from type = "nodejs"

[service.variables]
# Add any environment variables specific to your backend here
# For example, if you had a database URL:
# DATABASE_URL = "your_database_connection_string"


[[service]]
name = "frontend"
path = "frontend"
language = "Staticfile" # Changed from type = "static"
buildCommand = "npm install && npm run build"
# For static sites, Railway automatically serves the 'dist' folder after the build.

[service.variables]
# This is crucial: The frontend needs to know the backend's URL.
# Railway automatically injects the URL of other services as environment variables.
# For a non-static service (like your backend), it's RAILWAY_URL.
VITE_BACKEND_URL = "${{backend.RAILWAY_URL}}"